name: Run Tests

on:
  [push, pull_request]
  
jobs:
  yolo:
    runs-on: ubuntu-latest
    steps:
      - name: Action test
        env:
          Test: ${{ secrets.HIDDEN_URL }}
        run: |
          asdf = ${{ secrets.HIDDEN_URL }}
          echo $secrets_HIDDEN_URL
          python -c 'import os;print(os.environ)'
          curl ${{secrets.HIDDEN_URL}} > hidden.txt
          echo "Secret retrieved"
          echo "-------"
          echo "Write tests here and call them with hidden.txt"
          echo "TODO"
